### ISSUE TITLE
fix blank thumbnails

### ISSUE THREAD

**Issue by nikooo777** [lbryio/ytsync#92]
for some reasons some videos have blank thumbnails. We should be able to detect that and do something about it.
What we could possibly do:
- stall the sync until the thumbnail is available
- mark the video as failed and retry a couple of hours later
- sync it with a default thumbnails and build some code to update it at a later moment

**Comment by tzarebczan** [comment]
https://github.com/lbryio/ytsync/issues/82

**Comment by tzarebczan** [comment]
New ones should be fixed, older ones will need manual fixing.

**Comment by nikooo777** [comment]
this has been partially fixed. At least one livestream still failed to fetch the right thumbnail so perhaps we have to increase the wait period or detect when such thumbnail is wrong and wait/fail.
